name: bga_dart_note
description: Dart Note
version: 1.0.1
homepage: https://github.com/bingoogolapple/dart-note
author: bingoogolapple <bingoogolapple@gmail.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  args: ^1.5.1
  decimal: ^0.3.0

dev_dependencies:
  test: ^1.0.0
