name: dart_note
description: Dart Note
version: 1.0.0
# homepage: https://www.example.com
author: bingoogolapple <bingoogolapple@gmail.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  path: ^1.4.1

dev_dependencies:
  test: ^1.0.0
